class Song {
  final String id;
  final String title;
  final String artist;
  final String songPath;
  final String coverPath;
  bool isFavorite;

  Song({
    required this.id,
    required this.title,
    required this.artist,
    required this.songPath,
    required this.coverPath,
    this.isFavorite = false,
  });

  // Sample songs list
  static List<Song> songs = [
    Song(
      id: '1',
      title: 'Hijab-e-Haya',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_1.mp3',
      coverPath: 'assets/covers/covers_1.jpg',
    ),
    Song(
      id: '2',
      title: 'Mere Warga',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_2.mp3',
      coverPath: 'assets/covers/covers_2.jpg',
    ),
    Song(
      id: '3',
      title: 'Teeji Seat',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_3.mp3',
      coverPath: 'assets/covers/covers_3.jpg',
    ),
    Song(
      id: '4',
      title: '12 Saal',
      artist: 'Bilal Saeed',
      songPath: 'assets/songs/songs_4.mp3',
      coverPath: 'assets/covers/covers_4.jpg',
    ),
    Song(
      id: '5',
      title: 'Afsanay',
      artist: 'Young Stunners',
      songPath: 'assets/songs/songs_5.mp3',
      coverPath: 'assets/covers/covers_5.jpg',
    ),
    Song(
      id: '6',
      title: 'Banjara',
      artist: 'Arjit Singh',
      songPath: 'assets/songs/songs_6.mp3',
      coverPath: 'assets/covers/covers_6.jpg',
    ),
    Song(
      id: '7',
      title: 'Bewafa',
      artist: 'Imran Khan',
      songPath: 'assets/songs/songs_7.mp3',
      coverPath: 'assets/covers/covers_7.jpg',
    ),
    Song(
      id: '8',
      title: 'Brown Munde',
      artist: 'Ap Dhillon',
      songPath: 'assets/songs/songs_8.mp3',
      coverPath: 'assets/covers/covers_8.jpg',
    ),
    Song(
      id: '9',
      title: 'Canada Cade',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_9.mp3',
      coverPath: 'assets/covers/covers_9.jpg',
    ),
    Song(
      id: '10',
      title: 'Kabhi mai Kabhi Tum',
      artist: 'Drama Company',
      songPath: 'assets/songs/songs_10.mp3',
      coverPath: 'assets/covers/covers_10.jpg',
    ),
    Song(
      id: '11',
      title: 'Pasoori',
      artist: 'Coke Studio',
      songPath: 'assets/songs/songs_11.mp3',
      coverPath: 'assets/covers/covers_11.jpg',
    ),
    Song(
      id: '12',
      title: 'Phir Milengai',
      artist: 'Coke Studio',
      songPath: 'assets/songs/songs_12.mp3',
      coverPath: 'assets/covers/covers_12.jpg',
    ),
    Song(
      id: '13',
      title: 'Ye Dunya',
      artist: 'Coke Studio',
      songPath: 'assets/songs/songs_13.mp3',
      coverPath: 'assets/covers/covers_13.jpg',
    ),
    Song(
      id: '14',
      title: 'Dark Love',
      artist: 'Sidhu Moosewala',
      songPath: 'assets/songs/songs_14.mp3',
      coverPath: 'assets/covers/covers_14.jpg',
    ),
    Song(
      id: '15',
      title: 'Devil',
      artist: 'Sidhu Moosewala',
      songPath: 'assets/songs/songs_15.mp3',
      coverPath: 'assets/covers/covers_15.jpg',
    ),
    Song(
      id: '16',
      title: 'Dillagi',
      artist: 'Rahat Fateh Ali Khan',
      songPath: 'assets/songs/songs_16.mp3',
      coverPath: 'assets/covers/covers_16.jpg',
    ),
    Song(
      id: '17',
      title: 'Donot Mind',
      artist: 'Young Stunners',
      songPath: 'assets/songs/songs_17.mp3',
      coverPath: 'assets/covers/covers_17.jpg',
    ),
    Song(
      id: '18',
      title: 'Legend',
      artist: 'Sidhu Moosewala',
      songPath: 'assets/songs/songs_18.mp3',
      coverPath: 'assets/covers/covers_18.jpg',
    ),
    Song(
      id: '19',
      title: 'Lehanga',
      artist: 'Jass Manak',
      songPath: 'assets/songs/songs_19.mp3',
      coverPath: 'assets/covers/covers_19.jpg',
    ),
    Song(
      id: '20',
      title: 'Kale je Libaas',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_20.mp3',
      coverPath: 'assets/covers/covers_20.jpg',
    ),
    Song(
      id: '21',
      title: 'Khamoshiyan',
      artist: 'Arjit Singh',
      songPath: 'assets/songs/songs_21.mp3',
      coverPath: 'assets/covers/covers_21.jpg',
    ),
    Song(
      id: '22',
      title: 'One Love',
      artist: 'Shubh',
      songPath: 'assets/songs/songs_22.mp3',
      coverPath: 'assets/covers/covers_22.jpg',
    ),
    Song(
      id: '23',
      title: 'Cold Hours',
      artist: 'Aleemrk',
      songPath: 'assets/songs/songs_23.mp3',
      coverPath: 'assets/covers/covers_23.jpg',
    ),
    Song(
      id: '24',
      title: 'Allay',
      artist: 'Ali Zafar',
      songPath: 'assets/songs/songs_24.mp3',
      coverPath: 'assets/covers/covers_24.jpg',
    ),
    Song(
      id: '25',
      title: 'Pehlai Bhi Mai',
      artist: 'Ranbir Kapoor',
      songPath: 'assets/songs/songs_25.mp3',
      coverPath: 'assets/covers/covers_26.jpg',
    ),
    Song(
      id: '26',
      title: 'Baari',
      artist: 'Bilal Saeed',
      songPath: 'assets/songs/songs_26.mp3',
      coverPath: 'assets/covers/covers_26.jpg',
    ),
    Song(
      id: '27',
      title: 'Calaboose',
      artist: 'Sidhu Moosewala',
      songPath: 'assets/songs/songs_27.mp3',
      coverPath: 'assets/covers/covers_27.jpg',
    ),
    Song(
      id: '28',
      title: 'Afreen',
      artist: 'Rahat Fateh Ali Khan',
      songPath: 'assets/songs/songs_28.mp3',
      coverPath: 'assets/covers/covers_28.jpg',
    ),
    Song(
      id: '29',
      title: 'DilliWaliye',
      artist: 'Bilal Saeed',
      songPath: 'assets/songs/songs_29.mp3',
      coverPath: 'assets/covers/covers_29.jpg',
    ),
    Song(
      id: '30',
      title: 'Forget About it',
      artist: 'Sidhu Moosewala',
      songPath: 'assets/songs/songs_30.mp3',
      coverPath: 'assets/covers/covers_30.jpg',
    ),
    Song(
      id: '31',
      title: 'GOAT',
      artist: 'Sidhu Moosewala',
      songPath: 'assets/songs/songs_31.mp3',
      coverPath: 'assets/covers/covers_31.jpg',
    ),
    Song(
      id: '32',
      title: 'Bijlee Bijlee',
      artist: 'Hardy Sandhu',
      songPath: 'assets/songs/songs_32.mp3',
      coverPath: 'assets/covers/covers_32.jpg',
    ),
    Song(
      id: '33',
      title: 'Insane',
      artist: 'AP DHILLON',
      songPath: 'assets/songs/songs_33.mp3',
      coverPath: 'assets/covers/covers_33.jpg',
    ),
    Song(
      id: '34',
      title: 'Introduction',
      artist: 'FARIS SHAFI',
      songPath: 'assets/songs/songs_34.mp3',
      coverPath: 'assets/covers/covers_34.jpg',
    ),
    Song(
      id: '35',
      title: 'Bijlee',
      artist: 'hardy Sandhu',
      songPath: 'assets/songs/songs_32.mp3',
      coverPath: 'assets/covers/covers_32.jpg',
    ),
    Song(
      id: '36',
      title: 'Kahani Suno 2.0',
      artist: 'Kaif Khalil',
      songPath: 'assets/songs/songs_36.mp3',
      coverPath: 'assets/covers/covers_30.jpg',
    ),
    Song(
      id: '37',
      title: 'Keh Len Dai',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_37.mp3',
      coverPath: 'assets/covers/covers_37.jpg',
    ),
    Song(
      id: '38',
      title: 'Didar',
      artist: 'Kaka',
      songPath: 'assets/songs/songs_38.mp3',
      coverPath: 'assets/covers/covers_38.jpg',
    ),
    Song(
      id: '39',
      title: 'Kesariya',
      artist: 'Ranbir Kapoor',
      songPath: 'assets/songs/songs_39.mp3',
      coverPath: 'assets/covers/covers_39.jpg',
    ),

    Song(
      id: '40',
      title: 'Lag Di Lahore Diya',
      artist: 'Guru Randhawa',
      songPath: 'assets/songs/songs_40.mp3',
      coverPath: 'assets/covers/covers_40.jpg',
    ),
    Song(
      id: '41',
      title: 'Sayyara',
      artist: 'Faheem Abdullah',
      songPath: 'assets/songs/songs_41.mp3',
      coverPath: 'assets/covers/covers_41.jpg',
    ),

    Song(
      id: '42',
      title: 'Aj Ki Raat',
      artist: 'Divya Kumar',
      songPath: 'assets/songs/songs_42.mp3',
      coverPath: 'assets/covers/covers_42.jpg',
    ),

    Song(
      id: '43',
      title: 'Aadat',
      artist: 'Atif Aslam',
      songPath: 'assets/songs/songs_43.mp3',
      coverPath: 'assets/covers/covers_43.jpg',
    ),

    // Add more songs here
  ];
}
